### PR TITLE
added getAccountInfo.php

### LINKED ISSUE #21: PHP FORM - get account info
Accepts starid. Returns the given fields data from the DB. Ex -> I send a request to PHP form some data. I send the star id with the request. The form takes the request, checks with the DB, and returns the data. 
Data needed – last signed in, role type, first name, last name

### PR DESCRIPTION
**Pull request by TheMinds3t**
Utilized session variables
Added getAccountInfo.php, takes starid (currently hardcoded) and returns f&l name, role and last access timestamp
Closes #21

### CODE REVIEW

**Comment by TheMinds3t** [comment]
Added dbAssist.php to specify database login information, as well as database location, in a backend web form. Intended purpose is to be admin panel, but currently accessible through login page for development purposes.

**Comment by kingyeet9048** [comment]
@TheMinds3t You have a merge conflict. Please fix it.

**Comment by TheMinds3t** [comment]
@kingyeet9048 @nameer1811 please review this merge to make sure the conflicts and content look good.

**Review by kingyeet9048 — APPROVED** [review]
Looks good. I wonder how the session timeout would work on the back end side.

**Pull request merged**
